### ISSUE TITLE
Error when loading module

### ISSUE THREAD

**Issue by chxp82q** [mut-ex/awesome-wm-slidebar#1]
Hello,

Loading the module by adding this line: `local slidebar = require('slidebar')` in any file, including `rc.lua`, produces a `C stack overflow`.

Specs:
* Arch Linux
* awesome v4.3 (non git version)

Thanks for your work!

**Comment by mut-ex** [comment]
Hey there! Sorry that you faced this problem. I made a little mistake which I have fixed. Can you try again with the latest commit? Thank you

**Comment by chxp82q** [comment]
The same error is still produced

**Comment by mut-ex** [comment]
Okay now it should *definitely* work. I normally use the awesome git version but I tried the latest fix on awesome 4.3 non-git version and it works now (I was able to reproduce your error and it is all ok now).

And make sure you re-clone/re-download the repository since I also changed the structure (contents of slidebar.lua are now within init.lua) 

Thank you for trying it out and finding this bug

**Comment by chxp82q** [comment]
All good now!
