### ISSUE TITLE
Lag when setting transparent color for the bar

### ISSUE THREAD

**Issue by nivalderramas** [mut-ex/awesome-wm-slidebar#2]
Hi,
I was setting a bar and all it's running pretty nice, but when I use a transparent color for the background, the animation becomes so slow, is there any fix or do you have any idea to correct that?.

I'm using this code:
``` s.dock = slidebar{
  screen = s,
  bg = "#00ff001C",
  position = "left",
  size = 35,
  size_activator = 5,
  show_delay = 0,
  hide_delay = 0.10,
  }
```
Also I tried with the `opacity` property but it didn't work.

PS Thanks for sharing your bar, it's quite impressive

**Comment by mut-ex** [comment]
Hi, thank you!
Unfortunately the lag is because Awesome WM is single threaded, and slidebar's animations (currently) run synchronously. This produces smooth animations but the caveat is that computationally expensive operations like transparency being changed multiple times a second slow the main loop down.

That said, with the latest commit, I added a new configuration parameter, **_delta_**, which lets you specify how many pixels the bar moves in each step. With a transparent bar this greatly reduces the lag.

For example, my current configuration is:
```
      s.myslidebar = slidebar {
          screen = s,
          position = "left",
          bg = beautiful.bg_bar.."aa",
          size = 64
          easing = 1,
          show_delay = 0.50,
          hide_delay = 0.25,
          delta = 4,
      }
```
For now just make sure that the bar size is a multiple of delta. Hope that helps.

**Comment by nivalderramas** [comment]
Thanks!, I'm gonna try it

**Comment by nivalderramas** [comment]
@mut-ex  Guy, I'm creating an application for awesomewm too, but I'm new on this kind of stuff and I'd like to ask you a few questions, if you're ok with that, you can send me and email,
thanks again
